spring.application.name=Readscape
spring.datasource.url=jdbc:postgresql://ep-bold-dream-aw6n5by7-pooler.c-12.us-east-1.aws.neon.tech/neondb?user=neondb_owner&password=npg_w51vbfXeojmk&sslmode=require&channelBinding=require
spring.datasource.username=
spring.datasource.password= 